apiVersion: v1
kind: Service
metadata:
  name: unsorted-array-app-svc
  namespace: dev
spec:
  selector:
    app: unsorted-array-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
