name: Build and Publish Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'src/**'
    branches:
      - main
    tags:
      - 'v*'

env:
  PUBLIC_REGISTRY_URL: docker.io/messkon

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t unsorted-array-app:latest .

      - name: Tag Docker image
        run: |
          docker tag unsorted-array-app:latest $PUBLIC_REGISTRY_URL/unsorted-array-app:latest
          if [ "${{ github.ref_type }}" == "tag" ]; then
            docker tag unsorted-array-app:latest $PUBLIC_REGISTRY_URL/unsorted-array-app:${{ github.ref_name }}
          fi

      - name: Push Docker image
        run: |
          docker push $PUBLIC_REGISTRY_URL/unsorted-array-app:latest
          if [ "${{ github.ref_type }}" == "tag" ]; then
            docker push $PUBLIC_REGISTRY_URL/unsorted-array-app:${{ github.ref_name }}
          fi
