name: Formatting, Linting and Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install linting tools and requirements
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
        pip install --no-cache-dir -r requirements.txt
      working-directory: ./src

    - name: Run Black (code formatter)
      run: black --check --line-length 79 --diff .
      working-directory: ./src

    - name: Run Flake8 (linter)
      run: flake8 .
      working-directory: ./src

    - name: Run Unit Tests
      run: python -m unittest discover -s tests
      working-directory: ./src
